version: '3.0'

services:
  grafana:
    container_name: 'grafana-quickwit-datasource'
    build:
      context: ./.config
      args:
        grafana_version: 10.0.1
    ports:
      - 3000:3000/tcp
    volumes:
      - ./:/var/lib/grafana/plugins/grafana-quickwit-datasource
      - ./provisioning:/etc/grafana/provisioning
    # - ./grafana/storage:/var/lib/grafana
    # - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
