version: '3.0'

services:
  quickwit:
    image: quickwit/quickwit:edge
    environment:
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://localhost:7281
      - QW_ENABLE_OPENTELEMETRY_OTLP_EXPORTER=true
    command: ["run"]
    networks:
      - quickwit
    ports:
      - 7280:7280/tcp
  grafana:
    container_name: 'grafana-quickwit-datasource'
    build:
      context: ./.config
      args:
        grafana_version: 11.6.3
    ports:
      - 3000:3000/tcp
    volumes:
      - ./:/var/lib/grafana/plugins/grafana-quickwit-datasource
      - ./provisioning:/etc/grafana/provisioning
      - gquickwit:/var/lib/grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - quickwit

networks:
  quickwit:
    driver: bridge

volumes:
  gquickwit:
